### ISSUE TITLE
Compatible with CIM version 4.13.0?

### ISSUE THREAD

**Issue by hhanzo1** [diogofgm/TA-aruba_networks#1]
Testing (single Splunk 7.20 Docker instance) with CIM version 4.1.3.0 and Aruba Actions do not seem to appear.

**Comment by diogofgm** [comment]
Hi @pablo808,
Which data model are you testing against?
Which version of splunk are you running?
Is there a sanitised event you can show so I can test it?
Regards

**Comment by diogofgm** [comment]
I've found missing field extractions for the action and user on the authmgr. Already merged the changes in the repo.

**Comment by hhanzo1** [comment]
Data Model: Authentication
Splunk Version: 7.3.2

`Oct  3 23:59:56 2019 wc2 authmgr[4196]: <522008> <4196> <NOTI> <wc2 192.168.100.59>  User Authentication Successful: username=USER1 MAC=d0:c2:f3:dc:43:91 IP=192.168.1.154 role=authenticated VLAN=201 AP=AP5 SSID=guestnet AAA profile=Auth_AaaProfile auth method=802.1x auth server=acs1.test.com`

Thanks.

**Comment by diogofgm** [comment]
I've corrected that. Thank you for bringing it to my attention. I'll be releasing the new version today on Splunkbase.

**Comment by diogofgm** [comment]
Its already available in Splunkbase but you'll need to select the new version v0.1.1. The app inspect report is not out for this new version yet so I'll keep the v0.1.0 as default download for now.

**Comment by hhanzo1** [comment]
I have re-tested successfully. Thank you.
