### ISSUE TITLE
'action' lookup contains an extra space

### ISSUE THREAD

**Issue by hhanzo1** [diogofgm/TA-aruba_networks#2]
In the v0.1.1 release the lookup field 'action' in aruba_actions.csv contains an extra space. 
```
root@11f9ecf1ef82:/opt/splunk/etc/apps/TA-aruba_networks/lookups# more aruba_actions.csv
"vendor_action","action"
"Succeeded"," success"
"Successfully","success"
"Successful","success"
"failed"," failure"
"Failed"," failure"
"deny","blocked"
```
I checked the original v0.1.0 release and it looks like this was there too.  

Quick fix is just edit aruba_actions.csv and remove the preceding space.

**Comment by diogofgm** [comment]
Yes I noticed that swell. I just corrected it.
